name: Playwright Tests
on:
  push:
    branches: [ main, master, Dev/* ]
  pull_request:
    branches: [ main, master, Dev/* ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: ${{ contains(github.ref, 'Dev/') && 'Dev' || 'Prod' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Set environment variable
      run: echo "MY_ENVIRONMENT_VARIABLE=${{ vars.SECRET }}" >> $GITHUB_ENV
    - name: Install dependencies on ${{ vars.SECRET }}
      run: npm ci
    - name: Install Playwright Browsers on ${{ vars.SECRET }}
      run: npx playwright install --with-deps
    - name: Run Playwright tests on ${{ vars.SECRET }}
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
